### ISSUE TITLE
database

### ISSUE THREAD

**Issue by robinpreet** [berkaygurbuz/ecommerceWebSite-MVC#1]
can you tell how to connect database

**Comment by berkaygurbuz** [comment]
It was my first example with MVC so i did not use code-first. I used DB-First. You can create tables  with MSSQL by yourself and connect with DB-First. You can find tables and diagrams in readme.  [Click here tutorial about connection with DB-First.](https://www.entityframeworktutorial.net/entityframework6/create-entity-data-model.aspx)

**Comment by robinpreet** [comment]
Thank you for your response
